[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#c5a059"
backgroundColor = "#14161a"
secondaryBackgroundColor = "#1b1f27"
textColor = "#eceae5"
font = "sans serif"
